import * as fs from "fs";
import * as path from "path";

export class ReportService {
  constructor() {}

  public async exportHistoryToCSV(filePath: string, history: any[]): Promise<void> {
    const bom = "\uFEFF";
    const header = "时间,总资产数,存活资产数,存活率\n";
    const rows = history
      .map((item) => {
        const time = new Date(item.timestamp).toLocaleString();
        const rate =
          item.total_count > 0
            ? ((item.alive_count / item.total_count) * 100).toFixed(2)
            : "0.00";
        return `${time},${item.total_count},${item.alive_count},${rate}%`;
      })
      .join("\n");

    const content = bom + header + rows;
    await fs.promises.writeFile(filePath, content, "utf8");
  }

  public async exportHistoryToHTML(
    filePath: string,
    history: any[]
  ): Promise<void> {
    const timestamp = new Date().toLocaleString();
    const latest = history[history.length - 1] || {
      total_count: 0,
      alive_count: 0,
    };
    const latestRate =
      latest.total_count > 0
        ? ((latest.alive_count / latest.total_count) * 100).toFixed(2)
        : "0.00";

    const html = `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AssetPulse 存活趋势报告</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f0f2f5; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 12px rgba(0,0,0,0.1); }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #eaeaea; padding-bottom: 20px; }
        .header h1 { margin: 0; color: #1a1a1a; }
        .header p { color: #666; margin-top: 10px; }
        .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px; }
        .stat-card { background: #f8f9fa; padding: 20px; border-radius: 6px; text-align: center; border: 1px solid #e9ecef; }
        .stat-value { font-size: 24px; font-weight: bold; color: #007bff; }
        .stat-label { font-size: 14px; color: #6c757d; margin-top: 5px; }
        .stat-value.alive { color: #28a745; }
        .stat-value.rate { color: #fd7e14; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #dee2e6; }
        th { background-color: #f8f9fa; font-weight: 600; color: #495057; }
        tr:hover { background-color: #f8f9fa; }
        .footer { text-align: center; margin-top: 40px; color: #adb5bd; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>AssetPulse 存活趋势报告</h1>
            <p>生成时间: ${timestamp}</p>
        </div>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-value">${latest.total_count}</div>
                <div class="stat-label">最新总资产</div>
            </div>
            <div class="stat-card">
                <div class="stat-value alive">${latest.alive_count}</div>
                <div class="stat-label">最新存活数</div>
            </div>
            <div class="stat-card">
                <div class="stat-value rate">${latestRate}%</div>
                <div class="stat-label">最新存活率</div>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>时间节点</th>
                    <th>总资产数</th>
                    <th>存活资产数</th>
                    <th>存活率</th>
                </tr>
            </thead>
            <tbody>
                ${history
                  .slice()
                  .reverse()
                  .map((item) => {
                    const rate =
                      item.total_count > 0
                        ? ((item.alive_count / item.total_count) * 100).toFixed(
                            2
                          )
                        : "0.00";
                    return `
                <tr>
                    <td>${new Date(item.timestamp).toLocaleString()}</td>
                    <td>${item.total_count}</td>
                    <td>${item.alive_count}</td>
                    <td>${rate}%</td>
                </tr>
                `;
                  })
                  .join("")}
            </tbody>
        </table>

        <div class="footer">
            Generated by AssetPulse
        </div>
    </div>
</body>
</html>
    `;

    await fs.promises.writeFile(filePath, html, "utf8");
  }
}
